#!/bin/bash
# compile

# the example is:
# sed 's/\( [0-9]\) .*/\1/'
# outname=$(sed 's/^\.$/^$/' $1) ??

# does not work for some reason - which regex is used for that? any fault in the syntax or logic?
# outname=${$1/^\.$/^$}
# P_REP=${P/./_}

# this is bad
# echo "$1" | sed -e 's/^.*\..*$/^.*$/g'

outname=$(echo "$1" | sed -E 's/^(.*)\..*/\1/g')
g++-9 $1 -o $outname -std=c++2a

